HW-1
qwerty142/java-2023 pull request #1
Opened 2023-10-11 13:06 UTC by qwerty142

2023-10-15 18:35 UTC, Stasik371 requested changes

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Constants.java
> +    public static final int MAXSECONDS = 60;
В принципе это хороший паттерн, особенно прикольно так делать в котлине с его object, но есть одно пару нюансов:
1. Паттерн хорош, если эти константы не привязаны к 1 классу или алгоритму, зачем классу, который определяет палиндром иметь доступ к константе SECONDSINMINUTE?
2. Когда-нибудь этот класс превратится в мусорку со всеми-всеми константами приложения. Нам же не хочется иметь мусорку в коде, правда ж? :)

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        boolean indexOf = s.matches("\\d+:\\d\\d");
Прикольно, что ты знаешь регулярки)

Но она к сожалению неправильна... У нас есть строгий формат входного сообщения MM:ss
<img width="868" alt="image" src="https://github.com/qwerty142/java-2023/assets/90406808/8d342972-633e-452e-93cd-4acc35d485fa">

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        if (!indexOf) {
Кажется, что необязательно делать так)
Вот так чуть-чуть читабельнее, а то не очень понятно что за переменная indexOf
```
 if(!s.matches(...)) { 
    return -1; 
}
```

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        if (Integer.parseInt(pos[1]) >= MAXSECONDS) {
А зачем вводить еще 1 константу? Разве не будет читабельнее?
`        if (Integer.parseInt(pos[1]) >= SECONDS_IN_MINUTE) { `

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Constants.java
> +    public static final int SECONDSINMINUTE = 60;
А еще, константы в Java пишутся Upper Snake Case, т.е.

SECONDS_IN_MINUTE

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +            newDigit /= STEP;
И возникает третий нюанс из класса с константами) Чему равен STEP? Это мне нужно будет зайти в другой класс и посмотреть, а тут я могу отмотать вверх и все понять)

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task3.java
> +        for (int elem : firstArray) {
Это стоит вынести в отдельную функцию, метод довольно большой

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task3.java
> +        for (int elem : secondArray) {
И этот.. 

Посмотри в сторону классов Math и Arrays

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task5.java
> +    public static boolean isPalindromeDescendant(int value) {
Давай придерживаться золотого стандарта, что метод должен влезать в экран) Попробуй разнести, на несколько... Можно красиво сделать с рекурсией)

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +    public static int getKepler(int num, int steps) {
что такое Kepler?

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +import static edu.hw1.Constants.FINALRES;
Не особо понятно что такое FINAL_RESULT. Вроде даже в задании у этой константы есть имя ученого)

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        if (num < MINVALNUM) {
Давай, пожалуйста, валидировать входные данные:

> Выберем любое четырёхзначное число n, больше 1000, в котором не все цифры одинаковы.

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        for (int i = 0; i < curNum.length(); ++i) {
Лучше уходить от префикс-инкремента, он сбивает) Сразу возникают мысли: а почему нельзя пост инкремент написать

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        int upperNum = Integer.parseInt(new StringBuffer(numStr).reverse().toString());
А почему решил воспользоваться StringBuffer. Знаешь чем он отличается от StringBuilder?

2023-10-15 18:35 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        String numStr = IntStream.of(masOfNums).mapToObj(Integer::toString).collect(Collectors.joining(""));
Можно написать `Arrays.stream(masOfNums)`

А еще, будет очень круто, если каждую операцию стрима писать с новой строки, так читаемее)

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestFirstTask.java
> +    @Test @DisplayName("Общая длина видео в секундах") @ValueSource void CheckTask1() {
Такс) Тут будет большой комментарий, нужно будет выполнить его ко всем тестам) А еще нужно приучиться писать тесты по методологии ААА(или givenWhenThen, как здесь), прочитать можно [тута](https://habr.com/ru/articles/507594/)

Что хотелось бы видеть:

1. Один метод = один ТестКейс = один случай
2. Название класса = Название класса, который тестируешь + Test, `Task1Test`
3. Понятные названия методов из которых можно понять что происходит в тесте, например minutesToSeconds_shouldConvertIfToSecondsWithStandardValue (Мы в отделе делаем так, можно по-своему, но опять же, нужно передать суть)
4. Хочется комментариев с Arrange Act Assert(given when then) ***везде!!!!***
5. Скорее всего для данного случая тебе подойдут параметризированные тесты: вот [тут](https://www.baeldung.com/parameterized-tests-junit-5) есть хорошая статейка)
6. Каждая аннотация с новой строки
7. Осмысленно ставить аннотации и понять что лежит в пакете `org.junit.jupiter.params.provider`

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestFirstTask.java
> +    @Test @DisplayName("Общая длина видео в секундах") @ValueSource void CheckTask1() {
Нужно подогнать все тесты под этот коммент, будет не так быстро, но уверен, что у тебя получится)

Также обрати внимание, что ты сейчас неправильно оформил given when then, обязательно почитай статейку.

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestFirstTask.java
> +        int five = Task1.getSum("abc:df"); // fall from uncorrected symbols
Давай допишем тест на 0:59, должно возвращаться -1

А еще на отсутствие символа :

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestFirstTask.java
> +    @Test @DisplayName("Общая длина видео в секундах") @ValueSource void CheckTask1() {
А еще названия методов с маленькой буквы

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestTaskEight.java
> +                {1, 0, 1, 0, 1, 0, 1, 0},
Давай допишем тесты на то, что на доске все 1 или все 0

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestTaskFive.java
> +        assertThat(Task5.isPalindromeDescendant(num)).isEqualTo(result);
А что проверяет этот тест?) Выглядит как-будто ты вывел результат метода и прописал) (Это не камень в твой огород, просто реально так выглядит....)


Давай комментарием допишем цепочку

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestTaskFour.java
> +            Arguments.of("qwerty", "wqreyt"),
А можешь еще из задания примеров докинуть? Тут и везде

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestTaskSeven.java
> +            Arguments.of(8, 1, 4), // right
Давай допишем тестов на: 
- отрицательный сдвиг(тут сам решай, бросать ошибку или вызывать соседний метод
- когда число становится самим собой(16 -> 16)

На правый и левый сдвиг

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestTaskSix.java
> +            Arguments.of(6174, 0)};
Как-то очень мало тестов, нигде не проверяется корректный алгоритм, кроме константы)

Позаводи чиселок хотя бы из задания... А еще нужно добавить на 4 одинаковые цифры и на 5 значное число..

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestTaskSix.java
> +    @DisplayName("Количество ходов до числа Каплера") @ParameterizedTest @MethodSource("Tests")
Кстати можно писать вот так) 
<img width="672" alt="image" src="https://github.com/qwerty142/java-2023/assets/90406808/c67f6068-6adc-441e-aa65-60187f40b723">

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestTaskThree.java
> +            Arguments.of(new int[] {}, new int[] {1}, true),
А давай еще на null напишем тесты) Один или оба массива

2023-10-15 18:35 UTC, Stasik371 commented on src/test/java/edu/hw1/TestTaskSix.java
> +            Arguments.of(6174, 0)};
А еще, чтоб не возникало проблемы, как в задании на палиндром можно тоже комментом цепочку написать.

Это довольно специфичный случай, так не стоит делать везде

2023-10-15 18:57 UTC, qwerty142 commented on src/main/java/edu/hw1/Task1.java
> +        boolean indexOf = s.matches("\\d+:\\d\\d");
по поводу MM:SS там в примере есть "количество минут никак не ограничено, например, 999:59 является корректным входным значением"

2023-10-16 19:32 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        boolean indexOf = s.matches("\\d+:\\d\\d");
Я скорее про то, что 0:59 это невалидный формат

2023-10-17 03:07 UTC, merged