Homework 2
qwerty142/java-2023 pull request #3
Opened 2023-10-22 17:16 UTC by qwerty142

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/project1/Gdictionary.java
> +public class Gdictionary implements HangManDictionary {
А это почему в домашке №2?)

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Expr.java
> +        public String toString() {
Если пишешь какой-то код, то нужно написать на это тест)

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task2/Square.java
> +        public Square construct() {
Кажется, что метод не используется. Писать методы только для тестов плохой паттерн)

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task2/Rectangle.java
> +    public final static class Constructor {
Кажется, что можно обойтись без этого.

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +    private static final int[] MASSIVEFORRANDOM = new int[] {5, 2, 3, 4, 1, 8};
```suggestion
    private static final int[] MASSIVE_FOR_RANDOM = new int[] {5, 2, 3, 4, 1, 8};
```

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +    // Случайность невозможно тестировать так что для этого нужна отдельная функция
Ты прав, невозможно) Зато можно управлять коэффицентом из тестов)

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +    public Connection getConnection(boolean checkForTests) {
Писал выше про методы для тестов. Всегда можно обойтись без них.

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +        int randomIndex = random.nextInt(MASSIVEFORRANDOM.length);
а зачем танцы с бубнами и массивом?  Можно же из рандома получить число от 0 до 1

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task3/ConnectionTypes/FaultyConnection.java
> +        this.luckStatus = luckStatus;
Для чего нужна эта переменная?

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task3/ConnectionTypes/FaultyConnection.java
> +        logger.trace("Stable connection executed", command);
По заданию FaultyConnection должно всегда закрываться

2023-10-30 20:28 UTC, Stasik371 commented on src/main/java/edu/hw2/Task4/GetCallingData.java
> +        var info = new Throwable().getStackTrace()[1];
Давай передавать `Throwable` на вход)

2023-10-30 20:28 UTC, Stasik371 commented on src/test/java/edu/hw2/Task2Test.java
> +        rectangle = Rectangle.constructor.setWidth(10).setHeight(20).construct();
Отписал про construct() в самом коде

2023-10-31 13:39 UTC, qwerty142 commented on src/main/java/edu/hw2/Task3/ConnectionTypes/FaultyConnection.java
> +        logger.trace("Stable connection executed", command);
так оно наследуется от connection который в свою очередь наследуется от autocloseable

2023-11-11 15:07 UTC, dmskorikov requested changes

2023-11-11 15:07 UTC, dmskorikov commented on src/test/java/edu/hw2/Task1Test.java
> +    public void Constant_evaluate_shouldReternSameValueAsGot(double value, double expectedResult){
Тут для всех методов нарушены правила нейминга: методы должны всегда писаться в camelCase. Нужно разнести тесты разных классов по разным классам

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task2/Rectangle.java
> +    public static Constructor constructor;
Отдельный класс Constructor и соответствующее поле не нужны, так как это усложняет код. Достаточно так, как ты сделал: final поля width и height + для Square свой конструктор
Ненужный код нужно удалить

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task2/Rectangle.java
> +    public final static class Constructor {
+1 Нужно удалить

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task2/Square.java
> +    public Square() {
Дефолтный контруктор не нужен, надо удалить

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task2/Rectangle.java
> +    public Rectangle() {
Дефолтный конструктор не нужен, надо удалить

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionManagers/ConnectionManager.java
> +package edu.hw2.Task3.ConnectionManagers;
Для package свои [правила нейминга](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html#:~:text=Naming%20Conventions,a%20programmer%20at%20example.com%20.). Надо изменить для соответствия конвенциям

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +    private final double errorCheck;
Тут же храним вероятность поломки FaultyConnection? Поле нужно переменовать для соответствия

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +    private final Random random;
Так как значение этого поля не передается в конструкторе, то нужно инициализировать "по месту". Сейчас непонятно зачем оно в конструкторе

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +    private static final int[] MASSIVE_FOR_RANDOM = new int[] {5, 2, 3, 4, 1, 8};
Это нигде не используется - надо удалить

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +        if (errorCheck > randomNumber) {
:minor: Для наглядности лучше перевернуть условие - 'randomNumber < вероятность'

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionTypes/FaultyConnection.java
> +    private static Logger logger;
:minor: можно явно не объявлять логгер, а использовать соответствующу аннотацию lombok

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionTypes/FaultyConnection.java
> +        logger = LogManager.getLogger();
у тебя логгер - это статическое поле, поэтому его нужно или инициализировать по месту или в статическом init-блоке. А конструктор нужен для инициализации только нестатических полей. Нужно перенести инициализацию в место определения логгера (либо использовать lombok)

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionTypes/FaultyConnection.java
> +            throw new ConnectionException("Fatal try to connect");
Какая-то сильно хитрая логика, я бы предложил инициализировать FaultyConnection вероятностью (просто число от 0 до 1 в конструкторе), а сюда скопировал бы работу с Random из FaultyConnectionManager. Хитрая логика очень часто становится источником проблем, так как через какое-то время даже автор уже не помнит как оно работает и новые доработки могут ее поломать

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionTypes/FaultyConnection.java
> +    public void close() throws Exception {
Интерфейсы могут содержать реализацию методов по умолчанию, как раз чтобы не дублировать в каждом потомке одно и то же. Надо перенести в интерфейс

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionTypes/StableConnection.java
> +        if (command == null) {
Проверка параметров на входе 👍

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/PopularCommandExecutor.java
> +        logger = LogManager.getLogger();
То же самое замечание про иннициализацию логгера

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/PopularCommandExecutor.java
> +    public boolean workDone = false;
Это поле не нужно, надо удалить

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/PopularCommandExecutor.java
> +        workDone = true;
Не выполнено условие из задания:
`Если tryExecute не смог выполнить команду (превышено количество попыток), то нужно вернуть ConnectionException, при этом сохранив оригинальное исключение в параметре cause`

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task3/ConnectionManagers/DefaultConnectionManager.java
> +    private final int errorConnectionValue;
Это что-то из хитрой логики, про которую написал ниже. Нужно переделать на просто вероятность возврата FaultyConnection

2023-11-11 15:07 UTC, dmskorikov commented on src/test/java/edu/hw2/Task3Test.java
> +        var success = new DefaultConnectionManager(2, 0).getConnection();
Тут тоже вопросы к неймингу - почему success и fault? Лучше stable и faulty

2023-11-11 15:07 UTC, dmskorikov commented on src/test/java/edu/hw2/Task3Test.java
> +        assertThat(p.workDone).isTrue();
По условию, если не смогли, то нужно выбросить исключение. Поэтому workDone не нужен.
Для случая, когда выбросили исключение тоже нужно написать тест

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task4/GetCallingData.java
> +    public static Information callingInfo(Throwable throwable) {
По условию не нужно было передавать какой-то параметр. Какой сценарий использования тут предполагается?
Надо переделать на вызов без параметров и возвратом объекта класса CallingInfo из условия задачи

2023-11-11 15:07 UTC, dmskorikov commented on src/main/java/edu/hw2/Task4/Information.java
> +public record Information(String nameOfClass, String nameOfMethod) {
по условиям задачи класс должен называться CallingInfo

2023-11-11 15:07 UTC, dmskorikov commented on src/test/java/edu/hw2/Task4Test.java
> +    public void GetCallingInfo_shouldReturnNameAndClassWhereMethodWasCalled(){
Нужно соблюдать правила нейминга для методов

2024-05-03 18:20 UTC, merged